[package]
name = "bf_itp"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rocket = { version = "0.5.1", features = ["json"]}
serde = "1.0.213"
serde_json = "1.0.132"

[target.'cfg(all(target_arch = "aarch64", target_env = "gnu"))'.dependencies]
rppal = "0.20.0"